services:

  map_database:
    image: postgres:latest
    container_name: map_database
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./data:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 15s

  ss14mapserver:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: ss14mapserver
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - DOTNET_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://*:80
      # .NET SDK optimization for building
      - DOTNET_CLI_TELEMETRY_OPTOUT=1
      - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
      - DOTNET_CLI_HOME=/tmp
      - Auth__ApiKey=${AuthApiKey}
      - Github__AppWebhookSecret=${GitHubApiWebhookSecret}
    depends_on:
      map_database:
        condition: service_healthy
    volumes:
      - ./SS14.MapServer/appsettings.yaml:/app/appsettings.yaml
      - ./private-key.pem:/app/private-key.pem
      - ./files:/app/data
      - ./build:/app/build
    ports:
      - 5218:80
    post_start:
      - command: chown -R 20202:20202 /app
        user: root
    ulimits:
      core:
        hard: 0
        soft: 0
