services:

  map_database:
    image: postgres:latest
    container_name: map_database
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./data:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 15s

  ss14mapserver:
    image: ghcr.io/space-wizards/ss14.mapserver:latest
    container_name: ss14mapserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - DOTNET_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://*:80
      # .NET SDK optimization for building
      - DOTNET_CLI_TELEMETRY_OPTOUT=1
      - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
      - DOTNET_CLI_HOME=/tmp
    depends_on:
      map_database:
        condition: service_healthy
    volumes:
      - ./SS14.MapServer/appsettings.yaml:/app/appsettings.yaml
      - ./private-key.pem:/app/private-key.pem
    ports:
      - 5218:80
    ulimits:
      core:
        hard: 0
        soft: 0
