services:

  map_database:
    image: postgres:latest
    container_name: map_database
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./data:/var/lib/postgresql

  ss14mapserver:
    image: ghcr.io/space-wizards/ss14.mapserver:latest
    container_name: ss14mapserver
    volumes:
      - ./SS14.Mapserver/appsettings.yaml:/app/appsettings.yaml
      - ./private-key.pem:/app/private-key.pem
      - ./files:/app/data
      - ./build:/app/build
    ports:
      - 5218:80
    ulimits:
      core:
        hard: 0
        soft: 0
